package Selenium;// Generated by Selenium IDE
import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class CRUDTEST1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cRUDTEST1() {
    driver.get("http://localhost:3000/employees");
    driver.manage().window().setSize(new Dimension(786, 824));
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.name("title")).click();
    driver.findElement(By.name("title")).sendKeys("The Shining");
    driver.findElement(By.name("summary")).click();
    driver.findElement(By.name("summary")).sendKeys("Horror");
    driver.findElement(By.name("comedy")).click();
    driver.findElement(By.name("comedy")).sendKeys("0");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector("tr:nth-child(5) .btn:nth-child(1)")).click();
    driver.findElement(By.name("comedy")).click();
    driver.findElement(By.name("comedy")).click();
    {
      WebElement element = driver.findElement(By.name("comedy"));
      Actions builder = new Actions(driver);
      builder.doubleClick(element).perform();
    }
    driver.findElement(By.name("comedy")).sendKeys("1");
    driver.findElement(By.cssSelector(".btn-success")).click();
    driver.findElement(By.cssSelector("tr:nth-child(5) .btn:nth-child(3)")).click();
    driver.findElement(By.cssSelector("tr:nth-child(5) .btn-danger")).click();
  }
}
