package Selenium;// Generated by software.spence.Movies.Selenium IDE

import io.github.bonigarcia.wdm.WebDriverManager;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.util.HashMap;
import java.util.Map;

public class CRUDTEST10Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    WebDriverManager.chromedriver().setup();
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void cRUDTEST10() {
    driver.get("http://localhost:3000/");
    driver.manage().window().setSize(new Dimension(775, 824));
    driver.findElement(By.cssSelector(".btn-primary")).click();
    driver.findElement(By.name("title")).click();
    driver.findElement(By.name("title")).sendKeys("High Low");
    driver.findElement(By.name("summary")).click();
    driver.findElement(By.name("summary")).sendKeys("Noir");
    driver.findElement(By.name("comedy")).click();
    driver.findElement(By.name("comedy")).sendKeys("1");
    driver.findElement(By.cssSelector(".btn-success")).click();
  }
}
